CREATE TABLE quotes (
    id SERIAL,
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(255),
    due_date DATE,
    has_special_request BOOLEAN,
    special_request VARCHAR(255),
    product_name VARCHAR(255),
    product_color VARCHAR(255),
    create_artwork BOOLEAN,
    needs_designer BOOLEAN,
    small_quantity INT,
    medium_quantity INT,
    large_quantity INT,
    extra_large_quantity INT,
    two_extra_large_quantity INT,
    three_extra_large_quantity INT,
    four_extra_large_quantity INT,
    five_extra_large_quantity INT,
    price_per_shirt VARCHAR(255),
    total_price VARCHAR(255),
    artwork_image_url VARCHAR(255),
    additional_notes VARCHAR(255),
    CONSTRAINT pk_quotes PRIMARY KEY (id)
);