INSERT INTO categories (name, is_active) VALUES
('Standard', true),
('Premium', true),
('High-End', true),
('Triblends', true),
('50/50 cotton/polyester', true);

INSERT INTO styles (name, is_active) VALUES
('G500', true),
('3600', true),
('5026', true),
('5100', true),
('5020', true),
('IND300', true),
('G185', true),
('IND400', true);

INSERT INTO products (
    name,
    brand_id,
    style_id,
    description,
    is_active,
    is_product_visible_in_website,
    prices_per_color_on_white_clothes,
    prices_per_color_on_colored_clothes,
    available_sizes,
    sizes_info,
    available_clothe_size_parts,
    has_fiber_info,
    has_features_info,
    has_size_info,
    white_is_same_as_colored,
    clothe_packaging_type
) VALUES
(
    'Gildan Adult Heavy Cotton™ T-Shirt',
    5,
    4,
    'Your budget-friendly choice for events or giveaways. Simple, soft, and cost-effective, perfect for one-time use or casual gifting.',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 2.30}, "M":{"markup": 1.75, "originalPrice": 2.30}, "LG":{"markup": 1.75, "originalPrice": 2.30}, "XL":{"markup": 1.75, "originalPrice": 2.30}, "2XL":{"markup": 1.75, "originalPrice": 4.01}, "3XL":{"markup": 1.75, "originalPrice": 5.10}, "4XL":{"markup": 1.75, "originalPrice": 5.19}, "5XL":{"markup": 1.75, "originalPrice": 5.38}}',
    '{"S":{"markup": 1.75, "originalPrice": 2.30}, "M":{"markup": 1.75, "originalPrice": 2.30}, "LG":{"markup": 1.75, "originalPrice": 2.30}, "XL":{"markup": 1.75, "originalPrice": 2.30}, "2XL":{"markup": 1.75, "originalPrice": 4.01}, "3XL":{"markup": 1.75, "originalPrice": 5.10}, "4XL":{"markup": 1.75, "originalPrice": 5.19}, "5XL":{"markup": 1.75, "originalPrice": 5.38}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 0, "BODY WIDTH": 0, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 0}, "S": {"BODY LENGTH": 28, "BODY WIDTH": 18, "FULL BODY LENGTH": 28, "NECK CIRCUMFERENCE": 6.75, "SLEEVE LENGTH": 7.5}, "M": {"BODY LENGTH": 29, "BODY WIDTH": 20, "FULL BODY LENGTH": 29, "NECK CIRCUMFERENCE": 7.25, "SLEEVE LENGTH": 8}, "LG": {"BODY LENGTH": 30, "BODY WIDTH": 22, "FULL BODY LENGTH": 30, "NECK CIRCUMFERENCE": 7.75, "SLEEVE LENGTH": 8.5}, "XL": {"BODY LENGTH": 31, "BODY WIDTH": 24, "FULL BODY LENGTH": 31, "NECK CIRCUMFERENCE": 8.25, "SLEEVE LENGTH": 9}, "2XL": {"BODY LENGTH": 32, "BODY WIDTH": 26, "FULL BODY LENGTH": 32, "NECK CIRCUMFERENCE": 8.75, "SLEEVE LENGTH": 9.5}, "3XL": {"BODY LENGTH": 33, "BODY WIDTH": 28, "FULL BODY LENGTH": 33, "NECK CIRCUMFERENCE": 9.25, "SLEEVE LENGTH": 10}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 34, "NECK CIRCUMFERENCE": 9.75, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 35, "NECK CIRCUMFERENCE": 10.25, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": true}, {"name": "BODY WIDTH", "value": true}, {"name": "FULL BODY LENGTH", "value": true}, {"name": "NECK CIRCUMFERENCE", "value": true}, {"name": "SLEEVE LENGTH", "value": true}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'Next Level Apparel Unisex Cotton T-Shirt',
    11,
    5,
    'Designed for all-season versatility. Comfortable, reliable, and the perfect choice if youre looking to wear them at any occasion',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 3.40}, "M":{"markup": 1.75, "originalPrice": 3.40}, "LG":{"markup": 1.75, "originalPrice": 3.40}, "XL":{"markup": 1.75, "originalPrice": 3.40}, "2XL":{"markup": 1.75, "originalPrice": 4.81}, "3XL":{"markup": 1.75, "originalPrice": 6.00}, "4XL":{"markup": 1.75, "originalPrice": 7.92}, "5XL":{"markup": 1.75, "originalPrice": 8.67}}',
    '{"S":{"markup": 1.75, "originalPrice": 3.40}, "M":{"markup": 1.75, "originalPrice": 3.40}, "LG":{"markup": 1.75, "originalPrice": 3.40}, "XL":{"markup": 1.75, "originalPrice": 3.40}, "2XL":{"markup": 1.75, "originalPrice": 4.81}, "3XL":{"markup": 1.75, "originalPrice": 6.00}, "4XL":{"markup": 1.75, "originalPrice": 7.92}, "5XL":{"markup": 1.75, "originalPrice": 8.67}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27, "BODY WIDTH": 17.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7}, "S": {"BODY LENGTH": 28, "BODY WIDTH": 19, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7.5}, "M": {"BODY LENGTH": 29, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8}, "LG": {"BODY LENGTH": 30, "BODY WIDTH": 22, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8.5}, "XL": {"BODY LENGTH": 31, "BODY WIDTH": 24, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9}, "2XL": {"BODY LENGTH": 32, "BODY WIDTH": 26, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9.5}, "3XL": {"BODY LENGTH": 33, "BODY WIDTH": 28, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": true}, {"name": "BODY WIDTH", "value": true}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": true}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'AS Colour Classic T-Shirt',
    1,
    6,
    'When it comes to t-shirts, nothing compares to the superior feel and craftsmanship of this one.',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 7.60}, "M":{"markup": 1.75, "originalPrice": 7.60}, "LG":{"markup": 1.75, "originalPrice": 7.60}, "XL":{"markup": 1.75, "originalPrice": 7.60}, "2XL":{"markup": 1.75, "originalPrice": 9.10}, "3XL":{"markup": 1.75, "originalPrice": 9.10}, "4XL":{"markup": 1.75, "originalPrice": 9.10}, "5XL":{"markup": 1.75, "originalPrice": 9.10}}',
    '{"S":{"markup": 1.75, "originalPrice": 7.60}, "M":{"markup": 1.75, "originalPrice": 7.60}, "LG":{"markup": 1.75, "originalPrice": 7.60}, "XL":{"markup": 1.75, "originalPrice": 7.60}, "2XL":{"markup": 1.75, "originalPrice": 9.10}, "3XL":{"markup": 1.75, "originalPrice": 9.10}, "4XL":{"markup": 1.75, "originalPrice": 9.10}, "5XL":{"markup": 1.75, "originalPrice": 9.10}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27, "BODY WIDTH": 17.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7}, "S": {"BODY LENGTH": 28, "BODY WIDTH": 19, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7.5}, "M": {"BODY LENGTH": 29, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8}, "LG": {"BODY LENGTH": 30, "BODY WIDTH": 22, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8.5}, "XL": {"BODY LENGTH": 31, "BODY WIDTH": 24, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9}, "2XL": {"BODY LENGTH": 32, "BODY WIDTH": 26, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9.5}, "3XL": {"BODY LENGTH": 33, "BODY WIDTH": 28, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": false}, {"name": "BODY WIDTH", "value": false}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": false}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'As Colour Supply Crew',
    1,
    7,
    'Crewnecks that offer a sleek, modern look while keeping you cozy. Ideal for layering or wearing on their own.',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 15.75}, "M":{"markup": 1.75, "originalPrice": 15.75}, "LG":{"markup": 1.75, "originalPrice": 15.75}, "XL":{"markup": 1.75, "originalPrice": 15.75}, "2XL":{"markup": 1.75, "originalPrice": 17.75}, "3XL":{"markup": 1.75, "originalPrice": 17.75}, "4XL":{"markup": 1.75, "originalPrice": 17.75}, "5XL":{"markup": 1.75, "originalPrice": 17.75}}',
    '{"S":{"markup": 1.75, "originalPrice": 15.75}, "M":{"markup": 1.75, "originalPrice": 15.75}, "LG":{"markup": 1.75, "originalPrice": 15.75}, "XL":{"markup": 1.75, "originalPrice": 15.75}, "2XL":{"markup": 1.75, "originalPrice": 17.75}, "3XL":{"markup": 1.75, "originalPrice": 17.75}, "4XL":{"markup": 1.75, "originalPrice": 17.75}, "5XL":{"markup": 1.75, "originalPrice": 17.75}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27, "BODY WIDTH": 17.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7}, "S": {"BODY LENGTH": 28, "BODY WIDTH": 19, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7.5}, "M": {"BODY LENGTH": 29, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8}, "LG": {"BODY LENGTH": 30, "BODY WIDTH": 22, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8.5}, "XL": {"BODY LENGTH": 31, "BODY WIDTH": 24, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9}, "2XL": {"BODY LENGTH": 32, "BODY WIDTH": 26, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9.5}, "3XL": {"BODY LENGTH": 33, "BODY WIDTH": 28, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": false}, {"name": "BODY WIDTH", "value": false}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": false}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'AS Colour Long Sleeve Staple Shirt',
    1,
    8,
    'A cost-effective, longsleeve cotton t-shirt thats versatile enough for large events, organizations, or anyone looking for the most value during the colder months.',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 8.10}, "M":{"markup": 1.75, "originalPrice": 8.10}, "LG":{"markup": 1.75, "originalPrice": 8.10}, "XL":{"markup": 1.75, "originalPrice": 8.10}, "2XL":{"markup": 1.75, "originalPrice": 9.60}, "3XL":{"markup": 1.75, "originalPrice": 9.60}, "4XL":{"markup": 1.75, "originalPrice": 9.60}, "5XL":{"markup": 1.75, "originalPrice": 9.60}}',
    '{"S":{"markup": 1.75, "originalPrice": 8.10}, "M":{"markup": 1.75, "originalPrice": 8.10}, "LG":{"markup": 1.75, "originalPrice": 8.10}, "XL":{"markup": 1.75, "originalPrice": 8.10}, "2XL":{"markup": 1.75, "originalPrice": 9.60}, "3XL":{"markup": 1.75, "originalPrice": 9.60}, "4XL":{"markup": 1.75, "originalPrice": 9.60}, "5XL":{"markup": 1.75, "originalPrice": 9.60}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27, "BODY WIDTH": 17.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7}, "S": {"BODY LENGTH": 28, "BODY WIDTH": 19, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 7.5}, "M": {"BODY LENGTH": 29, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8}, "LG": {"BODY LENGTH": 30, "BODY WIDTH": 22, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 8.5}, "XL": {"BODY LENGTH": 31, "BODY WIDTH": 24, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9}, "2XL": {"BODY LENGTH": 32, "BODY WIDTH": 26, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 9.5}, "3XL": {"BODY LENGTH": 33, "BODY WIDTH": 28, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": false}, {"name": "BODY WIDTH", "value": false}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": false}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'Independent Heavyweight Crewneck Sweatshirt',
    7,
    9,
    'Heavyweight crewneck that offers a premium feel while feeling light as a feather',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 14.85}, "M":{"markup": 1.75, "originalPrice": 14.85}, "LG":{"markup": 1.75, "originalPrice": 14.85}, "XL":{"markup": 1.75, "originalPrice": 14.85}, "2XL":{"markup": 1.75, "originalPrice": 17.62}, "3XL":{"markup": 1.75, "originalPrice": 17.62}, "4XL":{"markup": 1.75, "originalPrice": 17.62}, "5XL":{"markup": 1.75, "originalPrice": 17.62}}',
    '{"S":{"markup": 1.75, "originalPrice": 14.85}, "M":{"markup": 1.75, "originalPrice": 14.85}, "LG":{"markup": 1.75, "originalPrice": 14.85}, "XL":{"markup": 1.75, "originalPrice": 14.85}, "2XL":{"markup": 1.75, "originalPrice": 17.62}, "3XL":{"markup": 1.75, "originalPrice": 17.62}, "4XL":{"markup": 1.75, "originalPrice": 17.62}, "5XL":{"markup": 1.75, "originalPrice": 17.62}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": false}, {"name": "5XL", "value": false}]',
    '{"XS": {"BODY LENGTH": 27.5, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 34.5}, "S": {"BODY LENGTH": 28.5, "BODY WIDTH": 21, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 35.5}, "M": {"BODY LENGTH": 29.5, "BODY WIDTH": 23, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 36.5}, "LG": {"BODY LENGTH": 30.5, "BODY WIDTH": 24.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 37.5}, "XL": {"BODY LENGTH": 31.5, "BODY WIDTH": 26.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 38.5}, "2XL": {"BODY LENGTH": 32.5, "BODY WIDTH": 27.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 39.5}, "3XL": {"BODY LENGTH": 33.5, "BODY WIDTH": 28.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 40.5}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": true}, {"name": "BODY WIDTH", "value": true}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": true}]',
    true,
    true,
    true,
    true,
    'TSHIRT'
),
(
    'Gildan Adult Heavy Blend™ Hooded Sweatshirt',
    5,
    10,
    'A budget-friendly hooded sweatshirt made with sturdy construction and a cotton-poly blended fleece fabric.',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 16.85}, "M":{"markup": 1.75, "originalPrice": 16.85}, "LG":{"markup": 1.75, "originalPrice": 16.85}, "XL":{"markup": 1.75, "originalPrice": 16.85}, "2XL":{"markup": 1.75, "originalPrice": 17.58}, "3XL":{"markup": 1.75, "originalPrice": 17.58}, "4XL":{"markup": 1.75, "originalPrice": 17.60}, "5XL":{"markup": 1.75, "originalPrice": 18.60}}',
    '{"S":{"markup": 1.75, "originalPrice": 16.85}, "M":{"markup": 1.75, "originalPrice": 16.85}, "LG":{"markup": 1.75, "originalPrice": 16.85}, "XL":{"markup": 1.75, "originalPrice": 16.85}, "2XL":{"markup": 1.75, "originalPrice": 17.58}, "3XL":{"markup": 1.75, "originalPrice": 17.58}, "4XL":{"markup": 1.75, "originalPrice": 17.60}, "5XL":{"markup": 1.75, "originalPrice": 18.60}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27.5, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 34.5}, "S": {"BODY LENGTH": 28.5, "BODY WIDTH": 21, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 35.5}, "M": {"BODY LENGTH": 29.5, "BODY WIDTH": 23, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 36.5}, "LG": {"BODY LENGTH": 30.5, "BODY WIDTH": 24.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 37.5}, "XL": {"BODY LENGTH": 31.5, "BODY WIDTH": 26.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 38.5}, "2XL": {"BODY LENGTH": 32.5, "BODY WIDTH": 27.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 39.5}, "3XL": {"BODY LENGTH": 33.5, "BODY WIDTH": 28.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 40.5}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": true}, {"name": "BODY WIDTH", "value": true}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": true}]',
    true,
    true,
    true,
    true,
    'HOODIE'
),
(
    'Independent Apparel Heavyweight Hooded Sweatshirt',
    7,
    11,
    'Premium hoodies that offer the perfect combination of warmth, durability, and style',
    true,
    true,
    '{"S":{"markup": 1.75, "originalPrice": 14.85}, "M":{"markup": 1.75, "originalPrice": 14.85}, "LG":{"markup": 1.75, "originalPrice": 14.85}, "XL":{"markup": 1.75, "originalPrice": 14.85}, "2XL":{"markup": 1.75, "originalPrice": 17.62}, "3XL":{"markup": 1.75, "originalPrice": 17.62}, "4XL":{"markup": 1.75, "originalPrice": 17.62}, "5XL":{"markup": 1.75, "originalPrice": 17.62}}',
    '{"S":{"markup": 1.75, "originalPrice": 14.85}, "M":{"markup": 1.75, "originalPrice": 14.85}, "LG":{"markup": 1.75, "originalPrice": 14.85}, "XL":{"markup": 1.75, "originalPrice": 14.85}, "2XL":{"markup": 1.75, "originalPrice": 17.62}, "3XL":{"markup": 1.75, "originalPrice": 17.62}, "4XL":{"markup": 1.75, "originalPrice": 17.62}, "5XL":{"markup": 1.75, "originalPrice": 17.62}}',
    '[{"name": "S", "value": true}, {"name": "M", "value": true}, {"name": "LG", "value": true}, {"name": "XL", "value": true}, {"name": "2XL", "value": true}, {"name": "3XL", "value": true}, {"name": "4XL", "value": true}, {"name": "5XL", "value": true}]',
    '{"XS": {"BODY LENGTH": 27.5, "BODY WIDTH": 20.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 34.5}, "S": {"BODY LENGTH": 28.5, "BODY WIDTH": 21, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 35.5}, "M": {"BODY LENGTH": 29.5, "BODY WIDTH": 23, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 36.5}, "LG": {"BODY LENGTH": 30.5, "BODY WIDTH": 24.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 37.5}, "XL": {"BODY LENGTH": 31.5, "BODY WIDTH": 26.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 38.5}, "2XL": {"BODY LENGTH": 32.5, "BODY WIDTH": 27.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 39.5}, "3XL": {"BODY LENGTH": 33.5, "BODY WIDTH": 28.5, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 40.5}, "4XL": {"BODY LENGTH": 34, "BODY WIDTH": 30, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 10.5}, "5XL": {"BODY LENGTH": 35, "BODY WIDTH": 32, "FULL BODY LENGTH": 0, "NECK CIRCUMFERENCE": 0, "SLEEVE LENGTH": 11}}',
    '[{"name": "BODY LENGTH", "value": true}, {"name": "BODY WIDTH", "value": true}, {"name": "FULL BODY LENGTH", "value": false}, {"name": "NECK CIRCUMFERENCE", "value": false}, {"name": "SLEEVE LENGTH", "value": true}]',
    true,
    true,
    true,
    true,
    'HOODIE'
);